- virtual youtuber
- product placement
- parody
- cat day
- looking at viewer
- multiple girls
- skeb commission
- textless version
- conversion
- gif
- bad id
- bad pixiv id
- bad seiga id
- absurdres
- commentary request
- translation request
- translated
- borrowed character
- animated