# start and end wildcards supported * (one at a time)
- alternate breast size*
- alternate muscle size
- virtual youtuber
- product placement
- parody
- cat day
- looking at viewer
- multiple girls
- skeb commission
- textless version
- conversion
- gif
- bad id
- bad pixiv id
- bad seiga id
- absurdres
- commentary request
- translation request
- translated
- borrowed character
- animated
- traditional bowtie
- crossover
- transparent background

#todo bra clothes shirt sweater lift