footwear:
  - boots
  - shoes
  - geta
eyewear:
  - glasses
  - goggles
  - sunglasses
  - monocle
headwear:
  - hat
  - crown
  - helmet
bandages:
  - bandaged
hair ornament:
  - hair flower
star (sky):
  - starry sky
multicolored:
  - two-tone
cup:
  - teacup
  - coffee cup
bag:
 - backpack
 - rucksack
bow:
  - bowtie
one eye closed:
  - wink
hoodie:
  - hood