footwear:
  - boots
  - shoes
  - geta
eyewear:
  - glasses
  - goggles
  - sunglasses
  - monocle
headwear:
  - hat
  - crown
  - helmet
bandages:
  - bandaged
hair ornament:
  - hair flower
star (sky):
  - starry sky
multicolored:
  - two-tone
cup:
  - teacup
  - coffee cup
bag:
 - backpack
 - rucksack
bow:
  - bowtie
one eye closed:
  wink
hoodie:
  - hood
short sleeves:
  - short over long sleeves
chinese clothes:
  - china dress
  - cheongsam
monochrome:
  - grayscale
dark skin:
 - dark-skinned
reptile:
  - lizard
stomach:
  - midriff
  - navel
navel:
  - midriff
clothes:
  - jacket
  - sweater
  - shirt
huge breasts:
  - gigantic breasts
large breasts:
  - huge breasts
sleeves past wrists:
  - sleeves past fingers
phone:
  - smartphone
denim:
  - jeans
pants:
  - jeans
instrument:
  - guitar
bandaid on leg:
  - bandaid on knee
pom pom (clothes):
  - pom pom hair ornament