synonyms:
  footwear: boots
  shoes: boots
  eye gear: glasses
  head gear: hat
  swimming suit: swimsuit
  eyewear: glasses
  headwear: hat
  fangs: fang
  stomach: navel
  midriff: navel
  bandages: bandaged
  frills: frilled
  blonde: white
  dog: wolf
  ear: ears