footwear: boots
eye gear: glasses
eyewear: glasses
head gear: hat
headwear: hat
swimming suit: swimsuit
fangs: fang
stomach: navel
midriff: navel
bandages: bandaged
frills: frilled
blonde: white
ear: ears
#sitting on person: sitting on face
#hair ornament: hair flower ornament
#todo dog extra ears?