footwear: boots
eye gear: glasses
eyewear: glasses
head gear: hat
headwear: hat
swimming suit: swimsuit
fangs: fang
stomach: navel
midriff: navel
bandages: bandaged
frills: frilled
blonde: white
ear: ears